### PR TITLE
DTGB-203: Updated codestyle.

### PR DESCRIPTION
**Pull request by delrueba**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.

### CODE REVIEW

**Review by meirege — APPROVED** [review]

**Review by meirege — CHANGES_REQUESTED** [review]
Update the changelog for the style guide AND gent_base with the correct information.

**Review by Jeroen005 — APPROVED** [review]

**Review by meirege — CHANGES_REQUESTED** [review]
@delrueba It seems the build server keeps failing on when we implement the gulp-axe-webdriver...
I've removed it from the package.json en yarn.lock files on the 8.x-3.x-dev branch for now to make sure the deploys are not failing anymore.
But this issue has to be solved before finalising this PR.

**Comment by delrueba** [comment]
And --save-dev did not help?
Keep in mind I'm also (slowly) working on this in the gulp refactor branch, let's keep communicating on this so we don't override our changes.

**Comment by meirege** [comment]
@delrueba no, I tried installing yarn without optionals but that just gave more errors. Some testing will be necessary I think.

**Comment by meirege** [comment]
@delrueba There are still some code climate issues in your PR :)

**Comment by delrueba** [comment]
@meirege stop reviewing this PR, it's not ready. You assigned yourself ;)

**Review by Jeroen005 — APPROVED** [review]

**Comment by meirege** [comment]
@delrueba Don't forget to refactor the starterkit/gulpfile.js too when you are done with the gulpfile.js!

**Comment by meirege** [comment]
Due to SassDoc implementation there will be a new gulp task "sassdoc".
This task should get run on watch (styles - sass files) and for all build tasks (the build server will have to generate the sassdoc directory).

**Comment by delrueba** [comment]
@meirege can we keep the starterkit gulpfile for a different issue?
It's technically independent.

**Comment by delrueba** [comment]
@meirege 
added iconfont and sassdoc tasks
not sure why iconfont is run as default task... I've kept it in the compile tasks for now.

@meirege, @Jeroen005 this was quite a big refactor, can you run each task and check if the result is as expected?
As said: images:minify is still a bit odd.

Some things to note:
- js:validate and styles:validate are now cached during watch. So you'll only get new errors for the updated files.
- axe is run on the validate task, I can't cache that task and it's too memory consuming to keep running it for all files. There are a lot of a11y violations though!

**Review by meirege — APPROVED** [review]

**Review by meirege — DISMISSED** [review]
Maybe add a gulp build version without the aXe validation? It's not very productive to have to wait for that task every time you need to build the code locally for development purposes...

**Comment by delrueba** [comment]
True, but I'm afraid only a limited number of developers will run the accessibility check if we don't force them to. Isn't that the same reason why we run the other validation tasks?

Furthermore, there should be no validation issues ;)
Even further: it's parallel, you don't have to wait.

**Comment by delrueba** [comment]
@meirege That task exists, it's 'compile'.
build executes compile and validate in parallel.

**Pull request merged**
