### PR TITLE
DTGB-174: Fixed role attribute.

### PR DESCRIPTION
**Pull request by meirege**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have updated the documentation accordingly.
- [x] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.

### CODE REVIEW

**Review by delrueba — DISMISSED** [review]
Best check the documentation too.

**Review by Jeroen005 — APPROVED** [review]
OK, als het ook op succes messages de correct role is @delrueba

**Comment by delrueba** [comment]
@Jeroen005 It was my suggestion originally, but I'll look into it. It does seem contradictory.

**Comment by delrueba** [comment]
OK, let's keep it on alert for now as the content of the message should help determine the nature of the alert.

We could use aria-live=polite, but I'm assuming even if these status messages are positive, it will be something the user should know immediately?

**Review by delrueba — APPROVED** [review]

**Pull request merged**
