### PR TITLE
Upgrade gulp and dependencies for node 10 compatibility

### PR DESCRIPTION
**Pull request by hstandaert**
## Description

Update gulp en npm dependencies in general.

## Motivation and Context

Builds are breaking since the node version on the build servers is upgraded to `v10.14.0`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.
- [ ] I have ran gulp axe on the compiled files and found no errors.

### CODE REVIEW

**Review by delrueba — APPROVED** [review]

**Comment by hstandaert** [comment]
@Jelle-S, important note is that there are some changes to the starterkit in order to make it work with node v10.14.0. These changes should also be applied in every project depending on gent-base..

I have no idea of the impact that this'll have.. Do you think this is a workable solution?

**Comment by Jelle-S** [comment]
I don't think there are many projects using the starterkit. Are the changes to starterkit breaking changes?

Projects using gent_base will have to be updated, but I don't think it'll have a big impact there either, it's just like any other theme/module update as far as I'm aware.

Travis still seems to be failing tho :)

**Comment by Jelle-S** [comment]
I'm also not sure if the 7.x version is affected?

**Comment by hstandaert** [comment]
@Jelle-S, all drupal projects with custom themes (which I understand are: all of them) are using starterkit. It's a skeleton theme that is used for new projects. 

@delrueba also pointed out that the build process used here originates from older projects, such as data portal (and idk which other projects), so it'll probably have to be updated there as well

**Comment by Jelle-S** [comment]
Ok, but as far as I understand these dependencies do not affect the generated css/js/templates. Which means the build process changes, but the end result doesn't, so the update should have no affect on the custom themes?

I would suggest making it work on node 10, and then deal with the problem of subthemes etc when we face them. My guess is it won't be much work besides probably updating some dependencies. The build process of the data portal now fails on the base theme, but the custom theme already builds since its dependencies are already updated.

**Pull request merged**
