### PR TITLE
Removed result-placeholder for checkbox-with-filter popup

### PR DESCRIPTION
**Pull request by hstandaert**
## Motivation and Context

[SGD8-681](https://digipolisgent.atlassian.net/browse/SGD8-681)

## Screenshots (if appropriate):
screenshot 2018-11-22 at 14 27 44

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.
- [ ] I have ran gulp axe on the compiled files and found no errors.

### CODE REVIEW

**Comment by hstandaert** [comment]
@delrueba, this is a breaking change so should be updated in other stakeholding projects, such as verwerkingsregister (and possible other I don't know of?).

Maybe we should park this until after the meeting of 29/11/2018. Do you it will be an issue in the mean time?

**Review by meirege — APPROVED** [review]

**Review by delrueba — CHANGES_REQUESTED** [review]
You cannot remove this.
It's a **live region** that let's you know the filter has been applied and how many results where found.

If you remove it, we can't autosubmit **and** need to implement a submit button.

**Comment by hstandaert** [comment]
@delrueba, I suggest you submit this comment to [SGD8-681](https://digipolisgent.atlassian.net/browse/SGD8-681) 😉

**Review by meirege — APPROVED** [review]

**Review by meirege — COMMENTED** [review]
Fix merge conflicts. :)

**Pull request closed without merging**
